# File managed by pluginsync
sudo: true
dist: trusty
language: go
go:
- 1.6.3
- 1.7.3
addons:
  apt:
    packages:
    - libvirt-bin
    - libvirt-dev
env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
  matrix:
  - TEST_TYPE=small
  - TEST_TYPE=build
matrix:
  exclude:
  - go: 1.6.3
    env: TEST_TYPE=build
before_install:
- "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"
install:
- cd $SNAP_PLUGIN_SOURCE
- make deps
script:
- make check 2>&1
notifications:
  email: false
  slack:
    secure: VkbZLIc2RH8yf3PtIAxUNPdAu3rQQ7yQx0GcK124JhbEnZGaHyK615V0rbG7HcVmYKGPdB0cXqZiLBDKGqGKb2zR1NepOe1nF03jxGSpPq8jIFeEXSJGEYGL34ScDzZZGuG6qwbjFcXiW5lqn6t8igzp7v2+URYBaZo5ktCS2xY=
before_deploy:
- "./scripts/pre_deploy.sh"
deploy:
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: RJR915t6OO3m/Gk1eMok3nB2J4xsNohNQxNc3sOGJ6KtcEn0MdRxzhXSklcMaA5U6RfQzQ6X58PKmj2rKenYK9yrboM3Ms7O+9wIpxgS/tLVrow/oCeHFjbgSuNZUgJoL2LX9FjtnlBXvV6RDnBJC2XXkzEgjsyRioFN+sk0jaDUAepZPKqKHTPXH/OVXUwPRwaBcL3824wejocEMVemfLP92fpbNXd1Hiq6y3R8E8js6r1gTqKpdjoPgCkIw1EYgo+bAPGQQFx1M+0OMKHMexeTWcXBO4hrZ1LuDrqA4suaT42ikelwdNgWxgUc2kgIJx42DTW+4JwPxr9wfWy+Ozgyy8o0vy0tdQWSXtY4atSAO613pNM3hciRi4CCte6J7QFzzrUzyijK4vvis3ZFIMessFoU4tb78//JomJ3G/Tu8XVpjhJoE1HmlEngyTCgO7mswQcTEuArOg17sLY1T7xPY9rwB4SVrhLfeymDL7saJclN65qcUresHBxQOXQaKPfR7g3YpKd0SjNflZAYBxnBsYwHPjmaaWxHBpiZSJ3e/4fOW/I9KpUi8ByesDFOTyJKyZdatX4A8HfWHwc0Eu3Ce9Wk7GQqshA1scZA/vywcTpEaYQD8jnW4mfqHnT6kQAzUntqzBtRMyxsFJ5ZkeSDliNXidVqWJvXGUk7Ygk=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-libvirt
    branch: master
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: s3
  access_key_id: AKIAINMB43VSSPFZISAA
  secret_access_key:
    secure: RJR915t6OO3m/Gk1eMok3nB2J4xsNohNQxNc3sOGJ6KtcEn0MdRxzhXSklcMaA5U6RfQzQ6X58PKmj2rKenYK9yrboM3Ms7O+9wIpxgS/tLVrow/oCeHFjbgSuNZUgJoL2LX9FjtnlBXvV6RDnBJC2XXkzEgjsyRioFN+sk0jaDUAepZPKqKHTPXH/OVXUwPRwaBcL3824wejocEMVemfLP92fpbNXd1Hiq6y3R8E8js6r1gTqKpdjoPgCkIw1EYgo+bAPGQQFx1M+0OMKHMexeTWcXBO4hrZ1LuDrqA4suaT42ikelwdNgWxgUc2kgIJx42DTW+4JwPxr9wfWy+Ozgyy8o0vy0tdQWSXtY4atSAO613pNM3hciRi4CCte6J7QFzzrUzyijK4vvis3ZFIMessFoU4tb78//JomJ3G/Tu8XVpjhJoE1HmlEngyTCgO7mswQcTEuArOg17sLY1T7xPY9rwB4SVrhLfeymDL7saJclN65qcUresHBxQOXQaKPfR7g3YpKd0SjNflZAYBxnBsYwHPjmaaWxHBpiZSJ3e/4fOW/I9KpUi8ByesDFOTyJKyZdatX4A8HfWHwc0Eu3Ce9Wk7GQqshA1scZA/vywcTpEaYQD8jnW4mfqHnT6kQAzUntqzBtRMyxsFJ5ZkeSDliNXidVqWJvXGUk7Ygk=
  bucket: snap.ci.snap-telemetry.io
  region: us-west-2
  skip_cleanup: true
  local-dir: s3
  upload-dir: plugins
  acl: public_read
  on:
    repo: intelsdi-x/snap-plugin-collector-libvirt
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
- provider: releases
  api_key:
    secure: EkgF7P/f0/OIfaw3XvA7I1nEuA8/ia/Tm0Yy+NYZQaioGIsGRxhCJ4OLJutwHOMxWZj6A4Yz9gvpcMh3lI6i0ZOxb2eFFU4MbNhAPm8qPjSD4sWmxt5DFojx5t53cvcb8WvE72LooceY9P1k58DsonMhB5Nz+DYR+ubZUD6tdYEE9UKEqepR9GCAEg6OZ773kRdmCXMz0jXxsZ7ki8eiQ5HqdFQq/3yPxA+hbn5NWaurcvdMiBAq6mCJVgoVeLWMmIQCvMEA33VING5h/kIfelpFEYX+kBEOzIk2S61YBSpu3DGLRBfock3A3wOGEAgXrpfSH220djqaO99P9ck7vh08Zxfc/PhIuCgRpVff7Ss+T/3DuG1aXGqzX70vth/sAqEF+jU8DPv4xFt27zUbqbxJkJbbeeRQI9o424k88r8sjKTdVNOqHDguwCGRHds0BMK4gR0/Nm/EJudqfM13eiX6TtjAfCfwTgc6emhAdgB1D5CncjzOuI/9BrH/wd07+5Aojaist1V2OwA9rw3Bm2FoPZ4qo2+UvN9UZQtLYtH8IBuqucTTSh4RKVPPLZ03wjDg+QqVFZvbxbG4biXCFZPmT2R809EVUacTqNcCjZfwEQvpf9aLLRiALrdcKREPSZx2IylicLzXy02vQEGBZetLK9Cot6xfZaWzg+aCExE=
  file:
    - release/snap-plugin-collector-libvirt_linux_x86_64
  skip_cleanup: true
  on:
    repo: intelsdi-x/snap-plugin-collector-libvirt
    tags: true
    condition: $TEST_TYPE = "build" && $TRAVIS_GO_VERSION = "1.7.3"
